ARG NODE_VERSION=20-slim

FROM node:${NODE_VERSION}

# Installs relevant development dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

# Expose '8080' inside the compose environment (which we will then map to in our compose file)
EXPOSE 8080

# NB: when 'overrideCommand = true' in devcontainer.json, this will be ignored
CMD ["tail", "-f", "/dev/null"]
