services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    networks:
      - development-network
    volumes:
      - ./:/project:cached
    environment:
      - CURRENT_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    networks:
      - development-network
    volumes:
      - ./:/project:cached
    environment:
      - CURRENT_ENV=development

networks:
  development-network:
    driver: bridge 
