services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: 
      - 8080:8080
    networks:
      - development-network
    volumes:
      - ./:/project:cached
      - frontend-dependency-cache:/project/frontend/node_modules
    environment:
      - CURRENT_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    networks:
      - development-network
    volumes:
      # Bind mount for reflective code changes
      - ./:/project:cached
      # Anonymous volume so that '.venv' is ignored from build
      - /project/backend/.venv
      # Cache for uv dependencies
      - backend-dependency-cache:/root/.cache/uv
    environment:
      - CURRENT_ENV=development

  db:
    image: postgres
    restart: always
    user: postgres
    networks:
      - development-network
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_admin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - development-network
    secrets:
      - db-admin-password
    environment:
      - PGADMIN_DEFAULT_EMAIL=johnnyb1694@gmail.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/db-admin-password
    ports:
      - 8888:80
    volumes:
      - db-admin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

secrets:
  db-password:
    file: db/secrets/password.txt
  db-admin-password:
    file: db/secrets/password-admin.txt

volumes:
  db-data:
  db-admin-data:
  frontend-dependency-cache:
  backend-dependency-cache:

networks:
  development-network:
    driver: bridge 
