services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    networks:
      - development-network
    volumes:
      - ./:/project:cached
      - frontend-dependency-cache:/project/frontend/node_modules
    environment:
      - CURRENT_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    networks:
      - development-network
    volumes:
      - ./:/project:cached
      - backend-dependency-cache:/root/.cache/pip
    environment:
      - CURRENT_ENV=development

volumes:
  frontend-dependency-cache:
    driver: local
  backend-dependency-cache:
    driver: local

networks:
  development-network:
    driver: bridge 
