ARG PYTHON_VERSION=python3.14-bookworm-slim

FROM ghcr.io/astral-sh/uv:${PYTHON_VERSION}

# Installs relevant development dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

# This enforces hard downloads of packages (rather than symlinks) as subsequent container builds
# can sometimes point to deprecated paths (so this is necessary)
# NB: a backend dependency cache is still maintained in the Docker Compose file
ENV UV_LINK_MODE=copy

# Run subsequent filesystem commands relative to this path
WORKDIR /project/backend

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
COPY . /project/backend

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

# Place executables in the environment at the front of the path
ENV PATH="/project/backend/.venv/bin:$PATH"

# Expose '8000' inside the compose environment (which we will then map to in our compose file)
EXPOSE 8000

# NB: when 'overrideCommand = true' in devcontainer.json, this will be ignored
CMD ["tail", "-f", "/dev/null"]
