ARG PYTHON_VERSION=3.14.2-slim

FROM python:${PYTHON_VERSION}

# Installs relevant development dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

# Expose '8000' inside the compose environment (which we will then map to in our compose file)
EXPOSE 8000

# NB: when 'overrideCommand = true' in devcontainer.json, this will be ignored
CMD ["tail", "-f", "/dev/null"]
